name: Export Cheaters to JSON

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:      # Allow manual runs

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout only needed files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            scripts/exportCheaters.js
            package.json
            package-lock.json
            cheaters.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install script dependencies
        run: cd scripts && npm ci

      - name: Decode service account key
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY_B64 }}" | base64 -d > serviceAccountKey.json
          echo "Service account key decoded and saved"

      - name: Run export script
        run: cd scripts && node exportCheaters.js

      - name: Commit and push cheaters.json
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add cheaters.json
          git commit -m 'Update cheaters.json [auto]' || echo 'No changes to commit'
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}

permissions:
  contents: write
